services:
    Netgen\Bundle\BetterIbexaAdminUIBundle\Tab\LocationView\TranslationsTab:
        decorates: Ibexa\AdminUi\Tab\LocationView\TranslationsTab
        arguments:
            - '@twig'
            - '@translator'
            - '@Ibexa\AdminUi\UI\Dataset\DatasetFactory'
            - '@Ibexa\Bundle\Core\Routing\UrlAliasRouter'
            - '@event_dispatcher'
            - '@form.factory'
            - '@Ibexa\Core\Repository\Permission\PermissionResolver'
            - '@ibexa.api.service.language'
            - '@Netgen\Bundle\BetterIbexaAdminUIBundle\Form\FormFactory'
