services:
    Netgen\Bundle\BetterIbexaAdminUIBundle\Tab\LocationView\TranslationsTab:
        decorates: Ibexa\AdminUi\Tab\LocationView\TranslationsTab
        decoration_inner_name: TranslationsTab.inner
        arguments:
            - '@TranslationsTab.inner'
            - '@Ibexa\Core\Repository\Permission\PermissionResolver'
            - '@Netgen\Bundle\BetterIbexaAdminUIBundle\Form\FormFactory'
            - '@twig'
            - '@translator'
            - '@event_dispatcher'
