services:
    netgen.better_ibexa_admin_ui.twig.runtime.better_ibexa_admin_ui:
        class: Netgen\Bundle\BetterIbexaAdminUIBundle\Templating\Twig\BetterIbexaAdminUIRuntime
        arguments:
            - "@ibexa.api.service.content"
        tags:
            - { name: twig.runtime }

    netgen.better_ibexa_admin_ui.twig.extension.better_ibexa_admin_ui:
        class: Netgen\Bundle\BetterIbexaAdminUIBundle\Templating\Twig\BetterIbexaAdminUIExtension
        tags:
            - { name: twig.extension }
