netgen.better_ibexa_admin_ui.content.update_always_available:
    path: /content/update-always-available
    methods: ['POST']
    controller: 'Netgen\Bundle\BetterIbexaAdminUIBundle\Controller\Content\UpdateAlwaysAvailable'
